# اسم یکتای اپلیکیشن توی Fly.io
app = "batimba98"    # ← اینو با یکتاترین اسمی که می‌خوای عوض کن

# Region پیش‌فرض (می‌تونی fra, ams, ord یا نزدیک‌ترین رو بگذاری)
primary_region = "ams"

[build]
  # اگر از Dockerfile استفاده می‌کنی  
  dockerfile = "Dockerfile"
  # یا اگر می‌خوای از Buildpacks استفاده کنی، خط بالارو کامنت کن و اینو فعال کن:
  # builder = "paketobuildpacks/builder:base"

[env]
  # این متغیرها رو بعداً با flyctl secrets ست می‌کنی
  BOT_TOKEN = ""  
  CHANNEL_ID = ""
  CHANNEL_USERNAME = ""
  ADMIN_ID = ""

[[services]]
  internal_port = 8080   # Flask یا برنامه‌ات این پورت رو استفاده میکنه
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
