app = "my-telegram-bot"  # این نام باید یکتـا باشه در Fly.io

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  BOT_TOKEN = "متغیر خالی بذار فعلاً"
  CHANNEL_ID = "متغیر خالی بذار فعلاً"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
